AllCops:
  Exclude:
    - features/**/*
    - .bundle/**/*
    - bundle_bin/**/*
    - lib/dwc_archive/ingester.rb
    - lib/dwc_archive/generator_meta_xml.rb
    - lib/dwc_archive/generator_eml_xml.rb
    - lib/dwc_archive/classification_normalizer.rb
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/DotPosition:
  EnforcedStyle: trailing

